#!/bin/bash

service::config_set() {
  config::check_or_set $1 $2 $SERVICE_CONFIG "${@:3}"
}

check() {
  if [ "$DEBUG" = "true" ]; then
    log::info "[DEBUG][service]: $SERVICE_CONFIG"
    cat $SERVICE_CONFIG
  fi

  # service::config_set SERVICE_GO_IDP_STORAGE_PORT text "Port" 8024

  service::config_set SERVICE_GO_IDP_STORAGE_BASE_DIR text "Base Dir" "/"

  service::config_set SERVICE_GO_IDP_STORAGE_OSS_ACCESS_KEY text "OSS_ACCESS_KEY"
  service::config_set SERVICE_GO_IDP_STORAGE_OSS_ACCESS_SECRET text "OSS_ACCESS_SECRET"
  service::config_set SERVICE_GO_IDP_STORAGE_OSS_BUCKET text "OSS_BUCKET"
  service::config_set SERVICE_GO_IDP_STORAGE_OSS_ENDPOINT text "OSS_ENDPOINT"

  service::config_set SERVICE_GO_IDP_STORAGE_OSS_BASE_DIR text "OSS_BASE_DIR" "/"
}

check $@
